### ISSUE TITLE
app closes right after i open it

### ISSUE THREAD

**Issue by nt5point1** [PlayXboxtion963/Riimote#4]
i am using android 9. i don't have any conflicting apps like motionserver, or wiimotedsu.

**Comment by PlayXboxtion963** [comment]
Thanks for your issue report,I has a test version which contains log display, Could you try to help me to debug this problem?

**Comment by PlayXboxtion963** [comment]
[https://github.com/PlayXboxtion963/DSU-AndroidServer/raw/48b96e39adeec82accb86e45f055a1e10c1bb45e/V1.6-withLogDisplay.apk](Debug Version)
Could you try this version?This version has log display,if problem happen again,pls send error log screenshot to me.Thanks

**Comment by nt5point1** [comment]
> [https://github.com/PlayXboxtion963/DSU-AndroidServer/raw/48b96e39adeec82accb86e45f055a1e10c1bb45e/V1.6-withLogDisplay.apk](Debug Version) Could you try this version?This version has log display,if problem happen again,pls send error log screenshot to me.Thanks

Log:
崩溃信息:
For input string: ",95"

类名:MainActivity.java

方法:onSensorChanged

行数:323

类型:java.lang.NumberFormatException

时间:2023-02-05_12:14

设备名称:Pixel XL

设备厂商:Google

系统版本:Android 9-28

CPU-ABI:arm64-v8a

versionCode:1

versionName:1.6

全部信息:
java.lang.NumberFormatException: For input string: ",95"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at com.plawyue.wiimotedsu.MainActivity$4.onSensorChanged(MainActivity.java:323)
	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:833)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6671)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by PlayXboxtion963** [comment]
Thanks for your reply,Give me some time to repair it.😉

**Comment by PlayXboxtion963** [comment]
Maybe i found problem,Are you using language is France or German？you can switch phone's language to English (US)， maybe you can try this way,if problem disappeared,pls reply to me.And i will release a version that repair this problem.

**Comment by PlayXboxtion963** [comment]
Thanks for your reply.
    I will release a new version that bug fixed tonight.I think this bug is associated with language.
   Some areas use ［ , ］ as decimal points,So this maybe cause trouble.
   Thank you for your report. It helps me a lot.😊😊😊
