### ISSUE TITLE
Not working with non-English languages

### ISSUE THREAD

**Issue by alr86** [PlayXboxtion963/Riimote#9]
My device language is Persian and when I open the app, Immediately get crash with this crash log:
https://paste.crdroid.net/mP50U9
```
time: 1732254174876
msg: java.lang.NumberFormatException: For input string: ".۰۳"
stacktrace: java.lang.NumberFormatException: For input string: ".۰۳"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:487)
	at com.plawyue.AndroidDSU.MainActivity$3.onSensorChanged(MainActivity.java:331)
	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:1179)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:349)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
```

(Android 14)

**Comment by PlayXboxtion963** [comment]
Thanks for your report . Next version will repair that .

**Comment by PlayXboxtion963** [comment]
[https://github.com/PlayXboxtion963/AndroidDSU/releases/tag/2.1](url) 
Repaired
